KoollaExample/Controllers/SellMoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KoollaExample.Models;
using System.Runtime.Serialization.Json;
using System.IO;
using System.Text;

namespace KoollaExample.Controllers
{
    public class SellMoreController : Controller
    {
        //
        // GET: /SellMore/

        public ActionResult Index()
        {
            if (Request.Cookies["UserId"] == null)
                return RedirectToAction("Login", "Account");
            return View();
        }

        public ActionResult Customer()
        {
            if (Request.Cookies["UserId"] == null)
                return RedirectToAction("Login", "Account");
            return View();
        }

        public ActionResult GroupMail()
        {
            if (Request.Cookies["UserId"] == null)
                return RedirectToAction("Login", "Account");
            return View();
        }

        public JsonResult CustomerRead()
        {
            JsonResult res = new JsonResult();
            res.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            if (Request.Cookies["UserId"] == null)
                return res;
            int id = int.Parse(Request.Cookies["UserId"].Value);
            List<MyCustomer> list = new List<MyCustomer>();
            using (var db = new koollaexampleEntities())
            {
                var c = db.customer.Where(p => p.uid == id).ToList();
                foreach (customer cus in c)
                {
                    var d = cus.deal.OrderByDescending(p => p.status).First();
                    MyCustomer mc = new MyCustomer(cus, d);
                    list.Add(mc);
                }
            }
            res.Data = list;
            return res;
        }

        public JsonResult CustomerUpdate()
        {
            JsonResult res = new JsonResult();
            res.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            if (Request.Cookies["UserId"] == null)
                return res;
            var models = Request.QueryString["models"];
            models = models.Substring(1, models.Length - 2);
            DataContractJsonSerializer serializer = new DataContractJsonSerializer(typeof(MyCustomer));
            var ms = new MemoryStream(Encoding.UTF8.GetBytes(models));
            var model = (MyCustomer)serializer.ReadObject(ms);



            using (var db = new koollaexampleEntities())
            {
                var oldC = db.customer.Where(p => p.cid == model.cid).Single();
                var oldD = oldC.deal.OrderByDescending(p => p.status).First();
                if (model.status.StatusId > oldD.status)
                {//success
                    var dbC = model.BuildDBCustomer(int.Parse(Request.Cookies["UserId"].Value));
                    var dbD = model.BuildDBDeal();
                    oldC.channel = dbC.channel;
                    oldC.company = dbC.company;
                    oldC.email = dbC.email;
                    oldC.money = dbC.money;
                    oldC.name = dbC.name;
                    oldC.phone = dbC.phone;
                    oldC.product = dbC.product;
                    oldC.deal.Add(dbD);
                }
                else if (model.status.StatusId == oldD.status)
                {
                    var dbC = model.BuildDBCustomer(int.Parse(Request.Cookies["UserId"].Value));
                    var dbD = model.BuildDBDeal();
                    oldC.channel = dbC.channel;
                    oldC.company = dbC.company;
                    oldC.email = dbC.email;
                    oldC.money = dbC.money;
                    oldC.name = dbC.name;
                    oldC.phone = dbC.phone;
                    oldC.product = dbC.product;
                }
                else
                {
                    res.Data = new { error = "不能将进展改变为之前的状态。" };
                }
                db.SaveChanges();
            }

            return res;
        }

        public JsonResult CustomerDestroy()
        {
            JsonResult res = new JsonResult();
            res.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            if (Request.Cookies["UserId"] == null)
                return res;
            var models = Request.QueryString["models"];
            models = models.Substring(1, models.Length - 2);
            DataContractJsonSerializer serializer = new DataContractJsonSerializer(typeof(MyCustomer));
            var ms = new MemoryStream(Encoding.UTF8.GetBytes(models));
            var model = (MyCustomer)serializer.ReadObject(ms);

            using (var db = new koollaexampleEntities())
            {
                var delete = db.customer.Where(p => p.cid == model.cid).Single();
                db.customer.Remove(delete);
                db.SaveChanges();
            }

            return res;
        }

        public JsonResult CustomerCreate()
        {
            JsonResult res = new JsonResult();
            res.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            if (Request.Cookies["UserId"] == null)
                return res;

            var models = Request.QueryString["models"];
            models = models.Substring(1, models.Length - 2);
            DataContractJsonSerializer serializer = new DataContractJsonSerializer(typeof(MyCustomer));
            var ms = new MemoryStream(Encoding.UTF8.GetBytes(models));
            var model = (MyCustomer)serializer.ReadObject(ms);

            var dbC = model.BuildDBCustomer(int.Parse(Request.Cookies["UserId"].Value));
            var dbD = model.BuildDBDeal();
            dbC.deal.Add(dbD);
            using (var db = new koollaexampleEntities())
            {
                db.customer.Add(dbC);
                db.SaveChanges();
            }
            var c = new MyCustomer(dbC, dbD);
            res.Data = c;
            return res;
        }

        public ActionResult CustomerNote(string id)
        {
            int cid = 0;
            try
            {
                cid = int.Parse(id);
            }
            catch (Exception)
            {
                ViewBag.Name = "您没有访问此客户的权限";
                return View();
            }
            if (Request.Cookies["UserId"] == null)
            {
                ViewBag.Name = "您没有访问此客户的权限";
                return View();
            }
            using (var db = new koollaexampleEntities())
            {
                var c = db.customer.Where(p => p.cid == cid).Single();
                if (c.uid != int.Parse(Request.Cookies["UserId"].Value))
                {
                    ViewBag.Name = "您没有访问此客户的权限";
                    return View();
                }
                else
                {
                    var d = c.deal.OrderByDescending(p => p.status).First();
                    var dbC = new MyCustomer(c, d);
                    ViewBag.Name = dbC.name;
                    ViewBag.StatusName = dbC.status.StatusName;
                    ViewBag.ProductName = dbC.product.ProductName;
                    ViewBag.ChannelName = dbC.channel.ChannelName;
                    ViewBag.Money = dbC.money;
                    ViewBag.Phone = dbC.phone;
                    ViewBag.Email = dbC.email;
                    ViewBag.Cid = dbC.cid;
                }
            }
            return View();
        }


        public ActionResult Dashboard()
        {
            if (Request.Cookies["UserId"] == null)
                return RedirectToAction("Login", "Account");
            int uid = int.Parse(Request.Cookies["UserId"].Value);
            int monthIn = 0;
            int monthOpen = 0;
            int monthInP = 0;
            int monthOpenP = 0;
            using (var db = new koollaexampleEntities())
            {
                var customer = db.users.Where(u => u.uid == uid).Single().customer.ToList();
                foreach (customer cus in customer)
                {
                    var lastdeal = cus.deal.OrderByDescending(p => p.status).First();
                    DateTime now = DateTime.Now;
                    DateTime month = new DateTime(now.Year, now.Month, 1);
                    DateTime week = now.Date.AddDays(0 - (int)now.DayOfWeek);
                    if (lastdeal.date > month && (lastdeal.status == 5 || lastdeal.status == 6))
                    {//本月入账
                        monthIn += lastdeal.customer.money;
                        monthInP += 1;
                    }
                    var opendeal = cus.deal.Where(p => p.status == 4).SingleOrDefault();
                    if (opendeal != null && opendeal.date > month)
                    {//本月开户
                        monthOpen += opendeal.customer.money;
                        monthOpenP += 1;
                    }
                }
            }
            if (monthOpen == 0)
                ViewBag.rate = 0;
            else
                ViewBag.rate = ((double)monthIn / monthOpen * 100).ToString("F1");
            if (monthOpenP == 0)
                ViewBag.rate2 = 0;
            else
                ViewBag.rate2 = ((double)monthInP / monthOpenP * 100).ToString("F1");
            if (monthInP == 0)
                ViewBag.average = 0;
            else
                ViewBag.average = ((double)monthIn / monthInP).ToString("F1");
            ViewBag.monthIn = monthIn;
            ViewBag.monthInP = monthInP;
            ViewBag.monthOpen = monthOpen;
            ViewBag.monthOpenP = monthOpenP;
            return View();
        }

        public JsonResult weeksell()
        {
            JsonResult res = new JsonResult();
            res.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            if (Request.Cookies["UserId"] == null)
                return res;
            int uid = int.Parse(Request.Cookies["UserId"].Value);

            int[] count = new int[9];
            int[] money = new int[9];
            using (var db = new koollaexampleEntities())
            {

KoollaExample/Views/SellMore/Customer.cshtml
@{
    ViewBag.Title = "Customer";
}
@section head{
    <link href="~/Content/kendoUI/style/kendo.common.min.css" rel="stylesheet" />
    <link href="~/Content/kendoUI/style/kendo.metro.min.css" rel="stylesheet" />
    <link href="~/Content/kendoUI/style/kendo.dataviz.min.css" rel="stylesheet" />
    <link href="~/Content/kendoUI/style/kendo.dataviz.metro.min.css" rel="stylesheet" />
    <script src="~/Content/kendoUI/js/kendo.all.min.js"></script>

    <link href="~/Content/SellMore.css" rel="stylesheet" />
    <script src="~/Scripts/sellmorecustomer.js"></script>
}
@section navbar{
<li>
    @Html.ActionLink("主页", "Index","Home")
</li>
<li>
    @Html.ActionLink("脉多", "Index","SellMore")
</li>
<li class="active">@Html.ActionLink("人脉", "Customer","SellMore")</li>
<li>@Html.ActionLink("群发", "GroupMail","SellMore")</li>
<li>@Html.ActionLink("统计", "Dashboard","SellMore")</li>
}

<div class="Sellmore-Container">
    <div class="head">
        <h1>人脉</h1>
        
    </div>
    <hr />
    <div id="grid"></div>
</div>

KoollaExample/Views/SellMore/CustomerNote.cshtml
@{
    ViewBag.Title = "CustomerNote";
}
@section head{
    <link href="~/Content/SellMore.css" rel="stylesheet" />

}
@section navbar{
<li>
    @Html.ActionLink("主页", "Index","Home")
</li>
<li>
    @Html.ActionLink("脉多", "Index","SellMore")
</li>
<li>@Html.ActionLink("人脉", "Customer","SellMore")</li>
<li class="active"><a href="/SellMore/CustomerNote/@ViewBag.Cid">@ViewBag.Name</a></li>
<li>@Html.ActionLink("群发", "GroupMail","SellMore")</li>
<li>@Html.ActionLink("统计", "Dashboard","SellMore")</li>
}

<div class="Sellmore-Container">
    <div class="head">
        <h1>@ViewBag.Name</h1>
        @ViewBag.StatusName, 金额 @ViewBag.Money, @ViewBag.ProductName, @ViewBag.ChannelName, 电话 @ViewBag.Phone, 电子邮件 @ViewBag.Email 
    </div>
    <hr />
    <h1>Note...Coming Soon...</h1>
</div>

KoollaExample/Views/SellMore/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}
@section head{
    <link href="~/Content/SellMore.css" rel="stylesheet" />

    <script src="~/Content/highCharts/highcharts.js"></script>
    <script src="~/Content/highCharts/exporting.js"></script>
    <script src="~/Content/highCharts/funnel.js"></script>
    <script src="~/Scripts/sellmoredashboard.js"></script>

}
@section navbar{
<li>
    @Html.ActionLink("主页", "Index","Home")
</li>
<li>
    @Html.ActionLink("脉多", "Index","SellMore")
</li>
<li>@Html.ActionLink("人脉", "Customer","SellMore")</li>
<li>@Html.ActionLink("群发", "GroupMail","SellMore")</li>
<li class="active">@Html.ActionLink("统计", "Dashboard","SellMore")</li>
}
<div class="Sellmore-Container">
    <h1>统计</h1>
    本月进账 @ViewBag.monthIn 元，开户 @ViewBag.monthOpen 元，资产到账率 @ViewBag.rate %，进账 @ViewBag.monthInP 人次，开户 @ViewBag.monthOpenP 人次，资产到账率 @ViewBag.rate2 %，平均每单 @ViewBag.average 元。
    <hr></hr>
    <div class="btn-group">
        <button class="btn btn-default" id="weeksell">本周业绩</button>
        <button class="btn btn-default" id="monthmoney">本月销售金额</button>
        <button class="btn btn-default" id="monthcount">本月销售数量</button>
        <button class="btn btn-default" id="sellfilter">销售漏斗</button>
        <button class="btn btn-default" id="routeanalyse">渠道分析</button>
        <button class="btn btn-default" id="lossreason">流失原因</button>
    </div>

    <div id="dashboard">

    </div>
</div>

KoollaExample/Views/SellMore/GroupMail.cshtml
@{
    ViewBag.Title = "GroupMail";
}
@section head{
    <link href="~/Content/SellMore.css" rel="stylesheet" />
    <script src="~/Scripts/sellmoreindex.js"></script>
}
@section navbar{
<li>
    @Html.ActionLink("主页", "Index","Home")
</li>
<li>
    @Html.ActionLink("脉多", "Index","SellMore")
</li>
<li>@Html.ActionLink("人脉", "Customer","SellMore")</li>
<li class="active">@Html.ActionLink("群发", "GroupMail","SellMore")</li>
<li>@Html.ActionLink("统计", "Dashboard","SellMore")</li>
}

<div class="Sellmore-Container">
    <h1>群发...Coming Soon...</h1>
    <hr />
</div>

KoollaExample/Views/SellMore/Index.cshtml
@{
    ViewBag.Title = "SellMore Index";
}
@section head{
    <link href="~/Content/SellMore.css" rel="stylesheet" />
}
@section navbar{
<li>
    @Html.ActionLink("主页", "Index","Home")
</li>
<li class="active">
    @Html.ActionLink("脉多", "Index","SellMore")
</li>
<li>@Html.ActionLink("人脉", "Customer","SellMore")</li>
<li>@Html.ActionLink("群发", "GroupMail","SellMore")</li>
<li>@Html.ActionLink("统计", "Dashboard","SellMore")</li>
}
<h1>SellMore Index...Coming Soon...</h1>